// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {  
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHiJSVUPZAj2B897goFyk0ISl4fD7R2kM',
    appId: '1:262897687935:web:26fec6c4e5d31055b30e4a',
    messagingSenderId: '262897687935',
    projectId: 'kalakriti-a6b8a',
    authDomain: 'kalakriti-a6b8a.firebaseapp.com',
    storageBucket: 'kalakriti-a6b8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcc_KjfWo6DMayn-NSbmLXvbH790_ZqzM',
    appId: '1:262897687935:android:933b361d8fd96639b30e4a',
    messagingSenderId: '262897687935',
    projectId: 'kalakriti-a6b8a',
    storageBucket: 'kalakriti-a6b8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOMs6Y10cbUgblwlxofYVqIMh9zyoNUfc',
    appId: '1:262897687935:ios:c39461d787b59627b30e4a',
    messagingSenderId: '262897687935',
    projectId: 'kalakriti-a6b8a',
    storageBucket: 'kalakriti-a6b8a.firebasestorage.app',
    iosBundleId: 'com.example.yourPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOMs6Y10cbUgblwlxofYVqIMh9zyoNUfc',
    appId: '1:262897687935:ios:c39461d787b59627b30e4a',
    messagingSenderId: '262897687935',
    projectId: 'kalakriti-a6b8a',
    storageBucket: 'kalakriti-a6b8a.firebasestorage.app',
    iosBundleId: 'com.example.yourPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHiJSVUPZAj2B897goFyk0ISl4fD7R2kM',
    appId: '1:262897687935:web:fb1774f0aa6873b5b30e4a',
    messagingSenderId: '262897687935',
    projectId: 'kalakriti-a6b8a',
    authDomain: 'kalakriti-a6b8a.firebaseapp.com',
    storageBucket: 'kalakriti-a6b8a.firebasestorage.app',
  );

}